[package]
name = "core_rs"

description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true


[dependencies]
rayon = "1.10.0"

anyhow.workspace = true
chrono.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
